const bikeModels1 = [
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (16).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (1).png",
    bikeImg3: "./imgs/bikes-grid/bike (3).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (4).jpg",
    name: "Model B82",
    frontSeat: "Comfortable",
    speed: "20 mph",
    price: "500",
    description:
      "The ultimate all-terrain companion, this model boasts a lightweight frame and responsive suspension for tackling rugged trails with ease. With its aerodynamic design and precision engineering, this bike offers unbeatable speed and agility for thrill-seeking riders.",
    type: "hybrid",
    suspension: "none",
    speed: 62,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },

  {
    bikeImg: "./imgs/bikes-transparent/bike-top (5).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (2).png",
    bikeImg3: "./imgs/bikes-grid/bike (4).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (5).jpg",
    name: "City I63",
    frontSeat: "Adjustable",
    speed: "25 mph",
    price: "600",
    description:
      "Designed for urban commuters, this bike features a sleek and minimalist frame combined with reliable disc brakes for confident city riding. Whether navigating crowded streets or cruising along bike paths, this model offers a smooth and comfortable ride for daily commuters.",
    type: "hybrid",
    suspension: "front",
    speed: 61,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (15).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (3).png",
    bikeImg3: "./imgs/bikes-grid/bike (5).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (6).jpg",
    name: "Explorer X41",
    frontSeat: "Padded",
    speed: "30 mph",
    price: "700",
    description:
      "Built for endurance, this bike is equipped with a carbon fiber frame and endurance geometry for long-distance rides in comfort. With its advanced drivetrain and responsive handling, this model delivers uncompromising performance for cyclists seeking to conquer epic journeys.",
    type: "hybrid",
    suspension: "none",
    speed: 69,
    frame: "Carbon Fiber",
    grupset: "Shimano",
    brakingSystem: "Rim brakes",
    wheel: "29-inch",
    velg: "Carbon Fiber",
    stang: "Alloy",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "SPD",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (13).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (4).png",
    bikeImg3: "./imgs/bikes-grid/bike (6).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (7).jpg",
    name: "Speed H90",
    frontSeat: "Comfortable",
    speed: "20 mph",
    price: "500",
    description:
      "Embrace the thrill of off-road adventures with this rugged mountain bike, featuring robust tires and powerful disc brakes for tackling challenging terrain. Engineered for maximum durability and agility, this model provides confidence-inspiring stability on even the most demanding trails.",
    type: "hybrid",
    suspension: "front",
    speed: 64,
    frame: "Steel",
    grupset: "SRAM",
    brakingSystem: "Disc brakes",
    wheel: "27.5-inch",
    velg: "Alloy",
    stang: "Steel",
    pedal: "Flat",
    transmission: "1x",
    cleat: "Look",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (3).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (5).png",
    bikeImg3: "./imgs/bikes-grid/bike (7).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (8).jpg",
    name: "Urban G25",
    frontSeat: "Adjustable",
    speed: "25 mph",
    price: "600",
    description:
      "Experience the freedom of exploration with this versatile gravel bike, equipped with wide tires and a sturdy frame for off-road adventures. Whether conquering gravel roads or venturing into the wilderness, this model offers unparalleled versatility and performance for adventurous riders.",
    type: "hybrid",
    suspension: "front",
    speed: 59,
    frame: "Aluminum",
    grupset: "Campagnolo",
    brakingSystem: "Rim brakes",
    wheel: "26-inch",
    velg: "Steel",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "3x",
    cleat: "Time",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (2).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (6).png",
    bikeImg3: "./imgs/bikes-grid/bike (8).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (9).jpg",
    name: "Street J14",
    frontSeat: "Padded",
    speed: "30 mph",
    price: "700",
    description:
      "Effortlessly blend style and functionality with this sleek and sophisticated urban cruiser, featuring a retro-inspired design and comfortable upright riding position. Perfect for leisurely rides around the city or weekend jaunts along scenic bike paths, this model combines timeless elegance with modern performance.",
    type: "mountain",
    suspension: "full",
    gears: 21,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (19).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (7).png",
    bikeImg3: "./imgs/bikes-grid/bike (9).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (10).jpg",
    name: "Adventure A49",
    frontSeat: "Leather",
    speed: "22 mph",
    price: "550",
    description:
      "Unleash your competitive spirit with this high-performance road bike, engineered for speed and efficiency with a lightweight frame and aerodynamic design. Whether sprinting to the finish line or tackling steep climbs, this model delivers unparalleled performance for serious road cyclists.",
    type: "mountain",
    suspension: "front",
    speed: 55,
    frame: "Carbon Fiber",
    grupset: "Shimano",
    brakingSystem: "Rim brakes",
    wheel: "29-inch",
    velg: "Carbon Fiber",
    stang: "Alloy",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "SPD",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (11).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (8).png",
    bikeImg3: "./imgs/bikes-grid/bike (10).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (11).jpg",
    name: "Model F31",
    frontSeat: "Gel",
    speed: "28 mph",
    price: "650",
    description:
      "Conquer the trails with confidence on this versatile hardtail mountain bike, featuring a durable aluminum frame and responsive front suspension for tackling technical terrain. With its agile handling and reliable components, this model is ready to take on anything the trail throws your way.",
    type: "mountain",
    suspension: "full",
    speed: 55,
    frame: "Steel",
    grupset: "SRAM",
    brakingSystem: "Disc brakes",
    wheel: "27.5-inch",
    velg: "Alloy",
    stang: "Steel",
    pedal: "Flat",
    transmission: "1x",
    cleat: "Look",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (18).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (9).png",
    bikeImg3: "./imgs/bikes-grid/bike (11).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (12).jpg",
    name: "Rider B97",
    frontSeat: "Ergonomic",
    speed: "24 mph",
    price: "590",
    description:
      "Discover new horizons with this versatile touring bike, designed for long-distance adventures and epic bikepacking journeys. Equipped with robust racks and comfortable geometry for all-day comfort, this model is ready to take you on unforgettable adventures across continents and beyond.",
    type: "mountain",
    suspension: "front",
    speed: 68,
    frame: "Aluminum",
    grupset: "Campagnolo",
    brakingSystem: "Rim brakes",
    wheel: "26-inch",
    velg: "Steel",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "3x",
    cleat: "Time",
  },

  {
    bikeImg: "./imgs/bikes-transparent/bike-top (7).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (10).png",
    bikeImg3: "./imgs/bikes-grid/bike (12).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (1).jpg",
    name: "Mountain C67",
    frontSeat: "Cushioned",
    speed: "21 mph",
    price: "510",
    description:
      "Experience the thrill of downhill racing with this purpose-built mountain bike, featuring a full suspension frame and aggressive geometry for maximum control and stability at high speeds. With its advanced suspension system and precision engineering, this model is built to dominate the most challenging descents.",
    type: "mountain",
    suspension: "full",
    speed: 75,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (6).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (11).png",
    bikeImg3: "./imgs/bikes-grid/bike (1).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (2).jpg",
    name: "City D50",
    frontSeat: "Memory Foam",
    speed: "26 mph",
    price: "620",
    description:
      "Elevate your trail riding experience with this full suspension mountain bike, featuring plush suspension and nimble handling for conquering technical descents and steep climbs. Whether shredding singletrack or exploring backcountry trails, this model offers unmatched performance and versatility for adventurous riders.",
    type: "electric",
    speed: 64,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (3).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (12).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Explorer I93",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "electric",
    speed: 70,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (2).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (13).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Speed E71",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "electric",
    speed: 60,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },

  {
    bikeImg: "./imgs/bikes-transparent/bike-top (7).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (14).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Model A39",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "electric",
    speed: 68,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (12).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (15).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Street B67",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "electric",
    speed: 65,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (20).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (16).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Street B67",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "hybrid",
    suspension: "none",
    speed: 62,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (21).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (17).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Street B67",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
  },
  {
    bikeImg: "./imgs/bikes-transparent/bike-top (22).png",
    bikeImg2: "./imgs/bikes-transparent/bike-top (1).png",
    bikeImg3: "./imgs/bikes-grid/bike (2).jpg",
    bikeImg4: "./imgs/bikes-grid/bike (3).jpg",
    name: "Street B67",
    frontSeat: "Mesh",
    speed: "29 mph",
    price: "680",
    description:
      "Redefine your daily commute with this innovative electric bike, offering pedal-assist technology and long-lasting battery life for effortless city riding. With its lightweight frame and powerful motor, this model makes commuting a breeze while reducing your carbon footprint and enhancing your daily routine.",
    type: "hybrid",
    suspension: "front",
    speed: 61,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
];
const faqQuestionsAnswers = [
  {
    question: "What types of bikes does Bike King Borders sell and repair?",
    answer:
      "Bike King Borders sells and repairs road, mountain, and hybrid bikes.",
  },
  {
    question: "What additional products does Bike King Borders sell?",
    answer:
      "In addition to bikes, Bike King Borders sells a range of bike accessories and clothing.",
  },
  {
    question: "Does Bike King Borders offer bike rentals?",
    answer:
      "Yes, Bike King Borders hires out bikes for daily use on nearby off-road bike trails.",
  },
  {
    question:
      "What sets Bike King Borders apart from other companies in the Borders region?",
    answer:
      "Bike King Borders is unique due to their location and the brilliant cycle trails nearby. They pride themselves on selling only quality products and guaranteeing servicing and repair.",
  },
  {
    question:
      "What social media platforms does Bike King Borders currently use?",
    answer:
      "Bike King Borders currently uses Facebook, Instagram, X, and YouTube to advertise their location, products, and services.",
  },
  {
    question: "Why does Bike King Borders want a dedicated website?",
    answer:
      "Bike King Borders wants a dedicated website to promote their business more effectively, appeal to a wide range of end-users, bring in more business and profits, and promote tourism in the area.",
  },
  {
    question: "Does Bike King Borders have major competitors nearby?",
    answer:
      "While Bike King Borders doesn’t have any major competitors nearby for servicing and repairs, they are in direct competition with larger companies for bike sales.",
  },
  {
    question:
      "What is Bike King Borders' focus when it comes to the quality of their products and services?",
    answer:
      "Bike King Borders focuses on selling only quality products and guarantees servicing and repair.",
  },
];

const feedbackSlider = [
  {
    id: 1,
    name: "Emily Jones",
    feedback:
      "Highly recommend Bike Kings for anyone looking for top-notch bikes and excellent customer service!",
    img: "./imgs/feedbackSlider/feedbackSlider (1).jpg",
  },
  {
    id: 2,
    name: "Michael Smith",
    feedback:
      "I've been a customer of Bike Kings for years, and they never disappoint. The quality of their bikes is unmatched!",
    img: "./imgs/feedbackSlider/feedbackSlider (2).jpg",
  },
  {
    id: 3,
    name: "Sarah Johnson",
    feedback:
      "Bike Kings made my biking experience incredible! Their staff is knowledgeable and friendly, making the whole process enjoyable.",
    img: "./imgs/feedbackSlider/feedbackSlider (3).jpg",
  },
  {
    id: 4,
    name: "David Brown",
    feedback:
      "Exceptional service from Bike Kings! I bought a bike for my son, and they went above and beyond to ensure we got exactly what we needed.",
    img: "./imgs/feedbackSlider/feedbackSlider (4).jpg",
  },
  {
    id: 5,
    name: "Jessica Wilson",
    feedback:
      "If you're in the market for a new bike, look no further than Bike Kings. They have a wide selection to choose from, and their team is incredibly helpful!",
    img: "./imgs/feedbackSlider/feedbackSlider (5).jpg",
  },
  {
    id: 6,
    name: "Matthew Taylor",
    feedback:
      "I had an amazing experience at Bike Kings. The staff was friendly and knowledgeable, and I found the perfect bike for my needs.",
    img: "./imgs/feedbackSlider/feedbackSlider (7).jpg",
  },
  {
    id: 7,
    name: "Emma Martinez",
    feedback:
      "Bike Kings exceeded my expectations! From the moment I walked in, I felt valued as a customer. I highly recommend them to anyone in need of a bike.",
    img: "./imgs/feedbackSlider/feedbackSlider (8).jpg",
  },
  {
    id: 8,
    name: "Daniel Anderson",
    feedback:
      "I can't thank Bike Kings enough for their outstanding service. They helped me find the perfect bike, and I couldn't be happier with my purchase.",
    img: "./imgs/feedbackSlider/feedbackSlider (9).jpg",
  },
  {
    id: 9,
    name: "Olivia Garcia",
    feedback:
      "Bike Kings made buying a bike a breeze! Their staff was friendly and helpful, and they had exactly what I was looking for.",
    img: "./imgs/feedbackSlider/feedbackSlider (10).jpg",
  },
  {
    id: 10,
    name: "William Rodriguez",
    feedback:
      "I had a fantastic experience at Bike Kings. Their team was attentive and patient, and they helped me find the perfect bike for my needs.",
    img: "./imgs/feedbackSlider/feedbackSlider (11).jpg",
  },
];
const feedbacks = [
  {
    id: 1,
    personName: "Emily Johnson",
    feedback:
      "Absolutely thrilled with the service at Bike King Borders! Their dedication to quality products and expert repairs sets them apart.",
    stars: 4,
    img: "./imgs/feedback/person (1).jpg",
  },
  {
    id: 2,
    personName: "David Martinez",
    feedback:
      "Bike King Borders made my cycling experience in the Borders region unforgettable with their top-notch bike rentals and friendly staff.",
    stars: 4,
    img: "./imgs/feedback/person (2).jpg",
  },
  {
    id: 3,
    personName: "Sarah Thompson",
    feedback:
      "Kudos to Bike King Borders for their excellent selection of bikes and accessories! I found everything I needed for my cycling adventures.",
    stars: 4.7,
    img: "./imgs/feedback/person (3).jpg",
  },
  {
    id: 4,
    personName: "Michael Brown",
    feedback:
      "Impressed by Bike King Borders' commitment to promoting tourism in the area. Their passion for cycling shines through in everything they do.",
    stars: 3.8,
    img: "./imgs/feedback/person (4).jpg",
  },
  {
    id: 5,
    personName: "Jessica Lee",
    feedback:
      "Had a fantastic experience shopping at Bike King Borders. Their staff was knowledgeable and helped me find the perfect bike for my needs.",
    stars: 4.9,
    img: "./imgs/feedback/person (5).jpg",
  },
  {
    id: 6,
    personName: "Christopher Nguyen",
    feedback:
      "Highly recommend Bike King Borders for all your cycling needs. Their dedication to customer satisfaction is unmatched!",
    stars: 5,
    img: "./imgs/feedback/person (6).jpg",
  },
  {
    id: 7,
    personName: "Amanda Wilson",
    feedback:
      "Bike King Borders' dedication to quality and service is evident in every aspect of their business. Proud to support such a reputable company.",
    stars: 4.6,
    img: "./imgs/feedback/person (7).jpg",
  },
  {
    id: 8,
    personName: "Daniel Taylor",
    feedback:
      "Thanks to Bike King Borders, I was able to explore the beautiful cycle trails in the Borders region with ease. Their rentals were top-notch!",
    stars: 4.9,
    img: "./imgs/feedback/person (8).jpg",
  },
  {
    id: 9,
    personName: "Rachel Lopez",
    feedback:
      "Bike King Borders' range of bike accessories and clothing is impressive. They have everything you need to enhance your cycling experience.",
    stars: 4.7,
    img: "./imgs/feedback/person (9).jpg",
  },
  {
    id: 10,
    personName: "Kevin King",
    feedback:
      "Exceptional service and attention to detail at Bike King Borders. They truly go above and beyond for their customers.",
    stars: 4.8,
    img: "./imgs/feedback/person (10).jpg",
  },
  {
    id: 11,
    personName: "Megan Campbell",
    feedback:
      "Bike King Borders' dedication to promoting cycling in the region is commendable. Proud to be a part of their community!",
    stars: 5,
    img: "./imgs/feedback/person (11).jpg",
  },
  {
    id: 12,
    personName: "Joshua Adams",
    feedback:
      "The staff at Bike King Borders are passionate about cycling and it shows. They provided me with invaluable advice and assistance.",
    stars: 4.5,
    img: "./imgs/feedback/person (12).jpg",
  },
  {
    id: 13,
    personName: "Lauren Garcia",
    feedback:
      "Bike King Borders' commitment to customer satisfaction is second to none. I'll definitely be returning for all my cycling needs.",
    stars: 4.9,
    img: "./imgs/feedback/person (13).jpg",
  },
  {
    id: 14,
    personName: "Ryan Rodriguez",
    feedback:
      "Thrilled with the level of service I received at Bike King Borders. They truly care about their customers and their cycling experience.",
    stars: 4.8,
    img: "./imgs/feedback/person (14).jpg",
  },
  {
    id: 15,
    personName: "Samantha Clark",
    feedback:
      "Bike King Borders exceeded my expectations with their excellent selection of bikes and accessories. A cyclist's paradise!",
    stars: 4.7,
    img: "./imgs/feedback/person (15).jpg",
  },
  {
    id: 16,
    personName: "Brandon Hernandez",
    feedback:
      "Impressed by the professionalism and expertise of the staff at Bike King Borders. They made my shopping experience enjoyable and stress-free.",
    stars: 4.6,
    img: "./imgs/feedback/person (16).jpg",
  },
  {
    id: 17,
    personName: "Jennifer Scott",
    feedback:
      "Thanks to Bike King Borders, I was able to find the perfect bike for my needs. Their attention to detail and personalized service are unmatched.",
    stars: 4.9,
    img: "./imgs/feedback/person (17).jpg",
  },
  {
    id: 18,
    personName: "Tyler Nguyen",
    feedback:
      "Bike King Borders is my go-to destination for all things cycling. Their commitment to quality and service is unmatched in the region.",
    stars: 4.8,
    img: "./imgs/feedback/person (18).jpg",
  },
  {
    id: 19,
    personName: "Emily Baker",
    feedback:
      "Highly recommend Bike King Borders to anyone passionate about cycling. Their dedication to excellence is truly inspiring!",
    stars: 5,
    img: "./imgs/feedback/person (19).jpg",
  },
  {
    id: 20,
    personName: "Nicholas Carter",
    feedback: "Great experience overall, would buy again. 4.7 stars.",
    stars: 4.7,
    img: "./imgs/feedback/person (20).jpg",
  },
];

const BikesTopSliderObjects = [
  {
    imageBike: "./imgs/bikes-transparent/bike-top (4).png",
    speedBike: "90km",
    kmphdBike: "30 KMPH",
    speedBikeHours: "4HOURS",
    speedBikeWeight: "18KG",
    titleBike: "Thunderbolt XT",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (6).png",
    speedBike: "90km",
    kmphdBike: "30 KMPH",
    speedBikeHours: "4HOURS",
    speedBikeWeight: "18KG",
    titleBike: "Trailblazer 5000",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (1).png",
    speedBike: "80km",
    kmphdBike: "28 KMPH",
    speedBikeHours: "3HOURS",
    speedBikeWeight: "16KG",
    titleBike: "Metro Trekker",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (2).png",
    speedBike: "50km",
    kmphdBike: "29 KMPH",
    speedBikeHours: "2HOURS",
    speedBikeWeight: "19KG",
    titleBike: "Speed E71",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (3).png",
    speedBike: "40km",
    kmphdBike: "33 KMPH",
    speedBikeHours: "3HOURS",
    speedBikeWeight: "12KG",
    titleBike: "Explorer Pro",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (15).png",
    speedBike: "42km",
    kmphdBike: "30 KMPH",
    speedBikeHours: "3HOURS",
    speedBikeWeight: "19KG",
    titleBike: "City Explorer",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (5).png",
    speedBike: "45km",
    kmphdBike: "32 KMPH",
    speedBikeHours: "4HOURS",
    speedBikeWeight: "29KG",
    titleBike: "City I63",
  },
  {
    imageBike: "./imgs/bikes-transparent/bike-top (17).png",
    speedBike: "28km",
    kmphdBike: "42 KMPH",
    speedBikeHours: "4HOURS",
    speedBikeWeight: "39KG",
    titleBike: "Adventure Hybrid",
  },
];

const locationObject = [
  {
   
    Edinburgh:
    `<iframe src=https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8937.277997029074!2d-3.098524!3d55.9438341!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4887b9a7365fccff%3A0x52629bc613f4b94b!2sEdinburgh%20College!5e0!3m2!1spl!2suk!4v1717182993590!5m2!1spl!2suk" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
    address: "24 Milton Rd E, Edinburgh EH15 2PQ"
  },
  {
    Glasgow:
    `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d71706.64946113205!2d-4.28028398541712!3d55.83086143098579!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4888441e1797b92f%3A0xec2975632e67711c!2sCity%20of%20Glasgow%20College!5e0!3m2!1spl!2suk!4v1717183532912!5m2!1spl!2suk" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
    address: "190 Cathedral St, Glasgow G4 0RF"
  },
  {
    Dundee: 
     
    `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d17624.57589375647!2d-3.0116497208984656!3d56.483747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48865d21cbe7ed07%3A0x10cf6238f48a437c!2sDundee%20and%20Angus%20College!5e0!3m2!1spl!2suk!4v1717183446998!5m2!1spl!2suk" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
    address: "Campus, Kingsway, Old Glamis Rd, Dundee DD3 8LE"
  },
  {
    Inverness:
    `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2145.1217299481164!2d-4.186688723474121!3d57.47626265794751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488f714c3da37437%3A0x4cf97bb804184f7e!2sUHI%20Inverness!5e0!3m2!1spl!2suk!4v1717183617682!5m2!1spl!2suk" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
      address: "Campus, 1, Inverness IV2 5NA"
  },
  {
    Aberdeen:
    `<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d34637.49550500418!2d-2.1288382046193592!3d57.139738120660084!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48840e17e7a14d39%3A0x39654090a0587f05!2sAberdeen%20College!5e0!3m2!1spl!2suk!4v1717183714368!5m2!1spl!2suk" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`,
      address: "Aberdeen City Campus, Gallowgate, Aberdeen AB25 1BN"
  },
];

const readMore = [
  {
    id: 0,
    text: [
      "Founded in 2023, Bike King Borders emerged from the founder's profound passion for cycling and a profound appreciation for the scenic beauty of the region it serves. With a vision extending beyond mere commerce, the company aims to become a cornerstone of the cycling community, offering more than just products and services but also a hub for enthusiasts to connect and share their love for the sport. This commitment to fostering a vibrant cycling culture has been integral to the company's growth, as it resonates with individuals who seek more than just transactions; they seek a sense of belonging and camaraderie within a community that shares their passion.",
      "Since its inception, Bike King Borders has remained dedicated to its core values of excellence and authenticity. Every product and service offered reflects this commitment, ensuring that customers receive not only top-notch gear but also a personalized experience tailored to their cycling needs. This dedication to quality has garnered the trust and loyalty of customers, establishing Bike King Borders as a reliable source for all things cycling-related in the region. Furthermore, the company's deep-rooted connection to the cycling culture permeates through every aspect of its operations, from the knowledgeable staff who are passionate about the sport to the events and initiatives aimed at bringing the community together.",
      "As Bike King Borders continues to grow, it remains steadfast in its mission to enrich the cycling experience for enthusiasts of all levels. Beyond just being a retailer, the company aspires to be a driving force behind the cycling scene in the region, organizing group rides, races, and community events that promote not only physical health but also a sense of camaraderie and belonging. By staying true to its founding principles and nurturing its relationship with the cycling community, Bike King Borders looks forward to a future where every cyclist feels supported, inspired, and empowered to explore the beautiful landscapes of the region on two wheels.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(1).jpg",
      "./imgs/readmore/readmore%20(2).jpg",
      "./imgs/readmore/readmore%20(3).jpg",
    ],
  },
  {
    id: 1,
    text: [
      "Bike King Borders, established in 2023, embodies a vision that extends far beyond the mere transaction of goods and services. At its core, the company was founded with the ambitious goal of nurturing a vibrant cycling community. This vision isn't just about selling bicycles or accessories; it's about creating a space where enthusiasts can come together, share their passion for the sport, and forge lasting connections. Since its inception, Bike King Borders has remained steadfast in its commitment to this ethos, recognizing that a thriving cycling culture is not only beneficial for business but also enriches the lives of individuals and the community at large.",
      " Driven by a dedication to excellence, Bike King Borders has experienced steady growth since its founding. This growth isn't solely measured in terms of revenue or market share but rather in the deepening of its roots within the cycling culture of the region it serves. By prioritizing quality products and services, the company has earned the trust and loyalty of its customers, establishing itself as a reliable and respected cornerstone of the cycling community. This commitment to excellence isn't just a business strategy; it's a reflection of Bike King Borders' genuine passion for cycling and its desire to provide enthusiasts with the best possible experience.",
      "Central to Bike King Borders' success is its profound connection to the cycling culture that thrives within the region. This connection isn't superficial but rather deeply ingrained in the company's DNA. From sponsoring local races and events to organizing group rides and community initiatives, Bike King Borders actively participates in and contributes to the vibrant cycling scene. This authentic engagement resonates with cyclists who seek more than just products; they seek a sense of belonging and camaraderie within a community that shares their passion. As Bike King Borders continues to grow and evolve, it remains committed to its founding principles, ensuring that the cycling community remains at the heart of everything it does.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(4).jpg",
      "./imgs/readmore/readmore%20(5).jpg",
      "./imgs/readmore/readmore%20(6).jpg",
    ],
  },
  {
    id: 2,
    text: [
      "At Bike King Borders, our mission extends far beyond the typical role of a retailer. We see ourselves as more than just a place to buy cycling equipment – we're your dedicated companion on your cycling journey. Whether you're an experienced cyclist searching for the latest high-performance gear or a novice enthusiast eager to explore the picturesque trails of our region, we're here to support you every step of the way. Our commitment to being your trusted partner means providing not only top-quality products but also expert guidance and personalized assistance to ensure that your cycling experience is nothing short of exceptional.",
      "Our carefully curated selection of cycling equipment reflects our dedication to serving cyclists of all backgrounds and skill levels. Whether you're passionate about conquering the open road, tackling rugged mountain terrain, or cruising through city streets, we have everything you need to fuel your cycling passion. From cutting-edge road bikes designed for speed and precision to durable mountain models built to withstand challenging trails, and versatile hybrid bikes perfect for urban commuting or leisurely rides, our comprehensive range of products caters to every style and preference. Each item in our inventory is handpicked to meet the highest standards of quality, performance, and durability, ensuring that you can confidently embark on your cycling adventures with gear you can trust.",
      "At Bike King Borders, we understand that cycling is more than just a hobby – it's a lifestyle. That's why we're dedicated to providing not only top-of-the-line equipment but also a supportive and inclusive community where cyclists can come together to share their passion and experiences. Whether you're joining us for one of our organized group rides, participating in a local cycling event, or simply stopping by our store for a friendly chat, you'll find a welcoming environment where cyclists of all backgrounds are celebrated and encouraged. With Bike King Borders as your trusted partner, you can embark on your cycling journey with confidence, knowing that you have the support and resources you need to achieve your goals and make lasting memories on the road or trail.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(7).jpg",
      "./imgs/readmore/readmore%20(8).jpg",
      "./imgs/readmore/readmore%20(9).jpg",
    ],
  },
  {
    id: 3,
    text: [
      "What distinguishes Bike King Borders from other cycling retailers is our steadfast dedication to quality and unwavering commitment to customer satisfaction. We believe that every cyclist deserves equipment and service that meet the highest standards, which is why we prioritize excellence in everything we do. Our team of seasoned technicians is not only passionate about cycling but also highly skilled in the art of bike maintenance and repair. Whether you're in need of a routine tune-up or a complex repair, you can trust our experts to deliver top-notch service that ensures your bike performs at its peak, mile after mile.",
      "At Bike King Borders, we take great pride in our meticulous attention to detail. We understand that even the smallest adjustments can make a significant difference in your cycling experience, which is why we approach every task with precision and care. From adjusting your bike's gears and brakes to fine-tuning its suspension and drivetrain, no detail is overlooked in our pursuit of perfection. Our goal is not just to fix your bike but to ensure that it's operating at optimal efficiency, allowing you to enjoy a smooth and seamless ride every time you hit the road or trail.",
      "What truly sets us apart, however, is our genuine dedication to keeping you rolling smoothly, mile after mile. We don't just see ourselves as service providers; we see ourselves as partners in your cycling journey, committed to supporting you every step of the way. Whether you're a seasoned rider with years of experience or a newcomer just starting out, you can count on Bike King Borders to provide the expertise, assistance, and personalized attention you need to achieve your cycling goals. With our team by your side, you can ride with confidence, knowing that your bike is in capable hands and that we're here to ensure your continued satisfaction and enjoyment of the sport.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(10).jpg",
      "./imgs/readmore/readmore%20(11).jpg",
      "./imgs/readmore/readmore%20(12).jpg",
    ],
  },
  {
    id: 4,
    text: [
      "Embark on your cycling journey and find the perfect ride to match your aspirations with Bike King Borders' premium selection of bikes. Whether you're a seasoned cyclist with a thirst for speed and precision on the open road or an adventurous spirit eager to conquer rugged mountain trails, we have the ideal model to fulfill your needs and elevate your riding experience. Our curated collection features top-of-the-line road bikes designed for high performance and maximum efficiency, as well as rugged mountain bikes built to withstand the toughest terrain and provide unmatched stability and control.",
      "For those who crave the thrill of the open road, our selection of high-performance road bikes offers unparalleled speed, agility, and responsiveness. Engineered with cutting-edge technology and precision craftsmanship, these bikes are designed to deliver an exhilarating riding experience, whether you're tackling a challenging climb or sprinting towards the finish line. With lightweight frames, aerodynamic designs, and top-of-the-line components, our road bikes are built to help you achieve your cycling goals and reach new levels of performance.",
      "If your heart belongs to the trails and you yearn for adventure in the great outdoors, our rugged mountain bikes are the perfect choice for you. Designed to tackle the toughest terrain with ease, these bikes are built to withstand the rigors of off-road riding and provide unparalleled stability, control, and durability. Whether you're navigating rocky descents, powering through technical climbs, or shredding through singletrack trails, our mountain bikes are ready to take on whatever challenges the trail throws your way. With features like responsive suspension systems, powerful disc brakes, and durable frames, our mountain bikes are built to help you explore new trails, conquer new obstacles, and experience the thrill of off-road adventure like never before.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(13).jpg",
      "./imgs/readmore/readmore%20(14).jpg",
      "./imgs/readmore/readmore%20(15).jpg",
    ],
  },
  {
    id: 5,
    text: [
      "Prepare for success on your cycling journey with Bike King Borders' comprehensive selection of gear and accessories. Whether you're gearing up for your daily commute or preparing for an epic adventure, we have everything you need to ride with confidence, comfort, and style. Our curated collection includes practical essentials like helmets, locks, and lights to keep you safe and visible on the road, as well as performance-enhancing components like pedals, saddles, and handlebars to optimize your riding experience and take your performance to the next level.",
      "Safety is paramount when it comes to cycling, which is why we offer a wide range of essential gear designed to protect you on every ride. Our selection of helmets features cutting-edge designs and advanced safety features to ensure maximum protection in the event of a fall or collision. Additionally, our high-quality locks and lights provide added security and visibility, giving you peace of mind as you navigate busy streets and dimly lit pathways.",
      "In addition to safety gear, we also offer a variety of performance-enhancing components to help you achieve your cycling goals. From premium pedals that provide optimal power transfer and efficiency to ergonomic saddles that offer unmatched comfort and support, our selection of components is designed to enhance your riding experience and optimize your performance. Whether you're looking to upgrade your existing setup or customize your bike to suit your individual needs and preferences, our knowledgeable staff is here to help you find the perfect gear to take your cycling to the next level. With Bike King Borders as your trusted partner, you can gear up for success and ride with confidence, knowing that you have everything you need to enjoy the ultimate cycling experience.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(16).jpg",
      "./imgs/readmore/readmore%20(17).jpg",
      "./imgs/readmore/readmore%20(18).jpg",
    ],
  },
  {
    id: 6,
    text: [
      "Elevate your cycling experience and ride in style with Bike King Borders' premium collection of cycling apparel and accessories. Whether you're hitting the road for a long-distance ride or exploring rugged trails in the great outdoors, our carefully curated selection combines performance-driven features with fashionable designs to ensure that you not only look good but also feel comfortable and confident on every ride. From sleek jerseys and padded shorts to weather-resistant jackets and versatile accessories, our collection has everything you need to ride in style, no matter where your journey takes you.",
      "Our range of cycling apparel is designed with both performance and style in mind, offering innovative features and technologies to enhance your comfort and performance on the bike. Our sleek jerseys are crafted from high-quality, moisture-wicking fabrics to keep you cool and dry during intense rides, while our padded shorts provide cushioned support and protection for long hours in the saddle. Additionally, our weather-resistant jackets offer protection from the elements, ensuring that you stay warm and dry in changing weather conditions.",
      "In addition to apparel, our collection also includes a variety of stylish accessories to complete your cycling ensemble and add a touch of flair to your ride. From colorful socks and caps to sleek sunglasses and gloves, our accessories are designed to complement your look and enhance your riding experience. Whether you're cycling through the city streets or tackling rugged trails in the wilderness, our stylish accessories are sure to turn heads and make a statement wherever you go.",
    ],
    imgs: [
      "./imgs/readmore/readmore%20(19).jpg",
      "./imgs/readmore/readmore%20(20).jpg",
      "./imgs/readmore/readmore%20(21).jpg",
    ],
  },
];
const bikeClothes1 = [
  {
    clothesImg: "./imgs/clothes/shorts (2).png",
    clothesImg2: "./imgs/clothes/shorts (2).png",
    clothesImg3: "./imgs/clothes/shorts (3).png",
    clothesImg4: "./imgs/clothes/shorts (4).png",
    name: "SpeedLite",
    type: "Shorts",
    price: 45.99,
    description:
      " Engineered for speed, SpeedLite shorts deliver a lightweight and aerodynamic fit, minimizing resistance and enhancing performance during competitive rides.",
  },
  {
    clothesImg: "./imgs/clothes/shorts (3).png",
    clothesImg2: "./imgs/clothes/shorts (2).png",
    clothesImg3: "./imgs/clothes/shorts (3).png",
    clothesImg4: "./imgs/clothes/shorts (4).png",
    name: "EnduroFit",
    type: "Shorts",
    price: 35.5,
    description: "Ideal for endurance cyclists, EnduroFit shorts provide superior cushioning and moisture-wicking properties, ensuring comfort and protection on extended journeys.",
  },


  {
    clothesImg: "./imgs/clothes/socks (5).png",
    clothesImg2: "./imgs/clothes/socks (2).png",
    clothesImg3: "./imgs/clothes/socks (3).png",
    clothesImg4: "./imgs/clothes/socks (4).png",
    name: "PedalPulse",
    type: "Socks",
    price: 16.75,
    description:
      "Designed for optimal performance, PedalPulse socks offer moisture-wicking fabric and a snug fit to keep your feet dry and comfortable during intense rides."
      
  },
  {
    clothesImg: "./imgs/clothes/socks (4).png",
    clothesImg2: "./imgs/clothes/socks (2).png",
    clothesImg3: "./imgs/clothes/socks (3).png",
    clothesImg4: "./imgs/clothes/socks (4).png",
    name: "TrailStride",
    type: "Socks",
    price: 10.75,
    description:
      "Perfect for off-road adventures, TrailStride socks feature reinforced cushioning and enhanced durability to protect your feet on rugged terrain.",
  },
  {
    clothesImg: "./imgs/clothes/socks (3).png",
    clothesImg2: "./imgs/clothes/socks (2).png",
    clothesImg3: "./imgs/clothes/socks (3).png",
    clothesImg4: "./imgs/clothes/socks (4).png",
    name: "UrbanSprint",
    type: "Socks",
    price: 10.75,
    description:
      "Tailored for city cyclists, UrbanSprint socks combine a stylish design with breathable materials to ensure comfort and flair on your daily commutes.",
  },
  {
    clothesImg: "./imgs/clothes/socks (2).png",
    clothesImg2: "./imgs/clothes/socks (2).png",
    clothesImg3: "./imgs/clothes/socks (3).png",
    clothesImg4: "./imgs/clothes/socks (4).png",
    name: "SpeedSwift",
    type: "Socks",
    price: 12.75,
    description:
      " Engineered for speed, SpeedSwift socks provide a lightweight and aerodynamic fit, reducing friction and boosting your cycling efficiency.",
  },
  {
    clothesImg: "./imgs/clothes/socks (1).png",
    clothesImg2: "./imgs/clothes/socks (2).png",
    clothesImg3: "./imgs/clothes/socks (3).png",
    clothesImg4: "./imgs/clothes/socks (4).png",
    name: "EnduroCool",
    type: "Socks",
    price: 10.75,
    description:
      " Ideal for long-distance rides, EnduroCool socks offer superior ventilation and targeted support, keeping your feet cool and comfortable throughout your journey.",
  },
  {
    clothesImg: "./imgs/clothes/shoes (1).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "VelocitySprint",
    type: "Shoes",
    price: 90.25,
    description:
      "The VelocitySprint shoes offer a lightweight and aerodynamic design, providing optimal power transfer and speed for competitive road cyclists.",
  },
  {
    clothesImg: "./imgs/clothes/shoes (2).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "TrailMaster",
    type: "Shoes",
    price: 96.25,
    description:
      "Built for mountain biking, TrailMaster shoes feature rugged soles and reinforced protection, ensuring durability and grip on rough and uneven terrains."
      
  },
  {
    clothesImg: "./imgs/clothes/shoes (3).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "UrbanStride",
    type: "Shoes",
    price: 44.25,
    description:
      "Designed for city commuting, UrbanStride shoes combine a sleek, casual look with comfortable, breathable materials for versatile, all-day wear"
    ,
  },
  {
    clothesImg: "./imgs/clothes/shoes (4).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "SpeedFusion",
    type: "Shoes",
    price: 35.25,
    description:
      "Engineered for performance, SpeedFusion shoes deliver an ergonomic fit with advanced ventilation, enhancing comfort and efficiency during high-speed rides.",
  },
  {
    clothesImg: "./imgs/clothes/shoes (5).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "EnduroTrack",
    type: "Shoes",
    price: 87.25,
    description:
      "Perfect for long-distance and endurance cycling, EnduroTrack shoes offer superior cushioning and support, reducing fatigue and improving comfort on extended journeys.",
  },
  {
    clothesImg: "./imgs/clothes/shoes (6).png",
    clothesImg2: "./imgs/clothes/shoes (2).png",
    clothesImg3: "./imgs/clothes/shoes (3).png",
    clothesImg4: "./imgs/clothes/shoes (4).png",
    name: "AeroGrip",
    type: "Shoes",
    price: 56.25,
    description:
      "Featuring a streamlined design and advanced grip technology, AeroGrip shoes ensure secure foot placement and maximum control, ideal for road racing and time trials.",
  },
  {
    clothesImg: "./imgs/clothes/jacket (1).png",
    clothesImg2: "./imgs/clothes/jacket (2).png",
    clothesImg3: "./imgs/clothes/jacket (3).png",
    clothesImg4: "./imgs/clothes/jacket (4).png",
    name: "CVeloShield",
    type: "Jackets",
    price: 15.99,
    description:
      "The VeloShield jacket offers windproof and water-resistant protection, ensuring you stay dry and comfortable in various weather conditions during your rides.",
  },
  {
    clothesImg: "./imgs/clothes/jacket (6).png",
    clothesImg2: "./imgs/clothes/jacket (2).png",
    clothesImg3: "./imgs/clothes/jacket (3).png",
    clothesImg4: "./imgs/clothes/jacket (4).png",
    name: "TrailBlazer",
    type: "Jackets",
    price: 15.99,
    description:
      " Built for off-road cyclists, the TrailBlazer jacket features rugged materials and enhanced breathability to keep you protected and comfortable on challenging trails."
      
  },
  {
    clothesImg: "./imgs/clothes/jacket (5).png",
    clothesImg2: "./imgs/clothes/jacket (2).png",
    clothesImg3: "./imgs/clothes/jacket (3).png",
    clothesImg4: "./imgs/clothes/jacket (4).png",
    name: "UrbanFlow",
    type: "Jackets",
    price: 15.99,
    description:
      "Designed for city cycling, the UrbanFlow jacket combines sleek style with reflective elements and lightweight fabric, perfect for navigating urban environments safely.",
  },
  {
    clothesImg: "./imgs/clothes/shorts (1).png",
    clothesImg2: "./imgs/clothes/shorts (2).png",
    clothesImg3: "./imgs/clothes/shorts (3).png",
    clothesImg4: "./imgs/clothes/shorts (4).png",
    name: "PedalPro",
    type: "Shorts",
    price: 20.5,
    description:
      "The PedalPro shorts feature high-performance fabric and ergonomic padding, providing maximum comfort and support for long-distance rides.",
  },
  {
    clothesImg: "./imgs/clothes/shorts (4).png",
    clothesImg2: "./imgs/clothes/shorts (2).png",
    clothesImg3: "./imgs/clothes/shorts (3).png",
    clothesImg4: "./imgs/clothes/shorts (5).png",
    name: "TrailFlex",
    type: "Shorts",
    price: 20.5,
    description:
      " Designed for mountain biking, TrailFlex shorts offer durable materials and extra reinforcement in key areas to withstand the toughest trails.",
  },
  {
    clothesImg: "./imgs/clothes/shorts (5).png",
    clothesImg2: "./imgs/clothes/shorts (2).png",
    clothesImg3: "./imgs/clothes/shorts (3).png",
    clothesImg4: "./imgs/clothes/shorts (4).png",
    name: "UrbanRide",
    type: "Shorts",
    price: 20.5,
    description:
      "Perfect for city commuting, UrbanRide shorts combine a stylish look with breathable, quick-drying fabric for all-day comfort and convenience.",
  },
  {
    clothesImg: "./imgs/clothes/jacket (2).png",
    clothesImg2: "./imgs/clothes/jacket (2).png",
    clothesImg3: "./imgs/clothes/jacket (3).png",
    clothesImg4: "./imgs/clothes/jacket (4).png",
    name: "Cycling Gilet",
    type: "Jackets",
    price: 55.75,
    description: "Lightweight vest for core protection and wind resistance.",
  },
 
  {
    clothesImg: "./imgs/clothes/jacket (3).png",
    clothesImg2: "./imgs/clothes/jacket (2).png",
    clothesImg3: "./imgs/clothes/jacket (3).png",
    clothesImg4: "./imgs/clothes/jacket (4).png",
    name: "Cycling Rain Jacket",
    type: "Jackets",
    price: 75.0,
    description:
      "Waterproof and breathable jacket for riding in rainy conditions.",
  },
  
];


const bikeAccessories1 = [
  {
    accessoriesImg: "./imgs/helmet/helmet (14).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "Velocity Viper",
    type: "Safety Gear",
    price: 32.99,
    description: "Designed for speed enthusiasts, this helmet offers superior aerodynamics and lightweight protection for high-velocity rides.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (13).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "AeroGuard",
    type: "Safety Gear",
    price: 35.99,
    description: "Featuring advanced ventilation and streamlined design, the AeroGuard ensures comfort and top-notch protection for long-distance cyclists.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (2).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "TrailBlazeUrbanShield",
    type: "Safety Gear",
    price: 30.99,
    description: " Built for rugged trails, this helmet combines durability and enhanced coverage to keep mountain bikers safe on challenging terrain.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (3).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "SpeedMaster",
    type: "Safety Gear",
    price: 38.99,
    description: "Perfect for city commuting, the UrbanShield offers a sleek look with reflective elements and multi-impact protection.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (4).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "EnduroX",
    type: "Safety Gear",
    price: 31.99,
    description: "Engineered for road racers, the SpeedMaster delivers optimal airflow and a snug fit to reduce drag and improve performance.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (5).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "SummitRider",
    type: "Safety Gear",
    price: 39.99,
    description: "Designed for enduro and off-road adventures, this helmet boasts a robust construction with extended rear coverage for added safety.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (6).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "ReflectoGuard",
    type: "Safety Gear",
    price: 32.99,
    description: "Prioritizing visibility, the ReflectoGuard integrates reflective materials and LED lights for enhanced safety during low-light conditions.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (7).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "Ventura Pro",
    type: "Safety Gear",
    price: 33.99,
    description: " A versatile helmet for all types of cyclists, the Ventura Pro combines comfort, durability, and advanced safety features.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (8).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "HyperShell",
    type: "Safety Gear",
    price: 37.99,
    description: "With a futuristic design and reinforced shell, the HyperShell provides maximum impact resistance and style.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (9).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "CruiseControl",
    type: "Safety Gear",
    price: 30.99,
    description: " Tailored for leisurely rides, the CruiseControl offers plush padding and an adjustable fit for ultimate comfort.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (10).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "PeakProtector",
    type: "Safety Gear",
    price: 31.99,
    description: "Designed for the most extreme conditions, the PeakProtector offers unparalleled protection and stability for serious cyclists.",
  },
  {
    accessoriesImg: "./imgs/helmet/helmet (11).png",
    accessoriesImg2: "./imgs/helmet/helmet (2).png",
    accessoriesImg3: "./imgs/helmet/helmet (3).png",
    accessoriesImg4: "./imgs/helmet/helmet (4).png",
    name: "TitaniumTrek",
    type: "Safety Gear",
    price: 30.99,
    description: " Combining lightweight titanium materials with a robust design, the TitaniumTrek ensures top-tier protection and longevity for all your biking adventures.",
  },
  {
    accessoriesImg: "./imgs/accesories/accessory (10).png",
    accessoriesImg2: "./imgs/accesories/accessory (11).jpg",
    accessoriesImg3: "./imgs/accesories/accessory (12).jpg",
    accessoriesImg4: "./imgs/accesories/accessory (1).jpg",
    name: "HydroGrip",
    type: "Utility",
    price: 9.99,
    description:
      "The HydroGrip water holder offers a secure and easy-to-access design, ensuring your bottle stays firmly in place even on bumpy rides.",
  },
  {
    accessoriesImg: "./imgs/accesories/bottle (4).png",
    accessoriesImg2: "./imgs/accesories/bottle (2).png",
    accessoriesImg3: "./imgs/accesories/bottle (3).png",
    accessoriesImg4: "./imgs/accesories/bottle (4).png",
    name: "AquaCage",
    type: "Utility",
    price: 12.99,
    description:
      "AquaCage combines lightweight materials with a sturdy frame, providing a reliable and durable option for holding your water bottle during any cycling adventure.",
  },
  {
    accessoriesImg: "./imgs/accesories/bottle (3).png",
    accessoriesImg2: "./imgs/accesories/bottle (2).png",
    accessoriesImg3: "./imgs/accesories/bottle (3).png",
    accessoriesImg4: "./imgs/accesories/bottle (4).png",
    name: "ThirstQuench",
    type: "Utility",
    price: 9.99,
    description:
      " Designed for quick hydration, ThirstQuench water holders feature an ergonomic design that allows for effortless bottle insertion and removal while riding.",
  },
  {
    accessoriesImg: "./imgs/accesories/bottle (2).png",
    accessoriesImg2: "./imgs/accesories/bottle (2).png",
    accessoriesImg3: "./imgs/accesories/bottle (3).png",
    accessoriesImg4: "./imgs/accesories/bottle (4).png",
    name: "FlowGuard",
    type: "Utility",
    price: 9.99,
    description:
      "With its sleek and aerodynamic profile, FlowGuard water holders minimize drag and keep your water bottle easily accessible, perfect for competitive cyclists."
      
  },
  {
    accessoriesImg: "./imgs/accesories/bottle (1).png",
    accessoriesImg2: "./imgs/accesories/bottle (2).png",
    accessoriesImg3: "./imgs/accesories/bottle (3).png",
    accessoriesImg4: "./imgs/accesories/bottle (4).png",
    name: "TrailHydra",
    type: "Utility",
    price: 9.99,
    description:" Built for off-road biking, the TrailHydra water holder offers reinforced stability and extra grip, ensuring your bottle stays put on the roughest terrains.",
  },
  {
    accessoriesImg: "./imgs/accesories/accessory (9).png",
    accessoriesImg2: "./imgs/accesories/accessory (10).png",
    accessoriesImg3: "./imgs/accesories/accessory (11).jpg",
    accessoriesImg4: "./imgs/accesories/accessory (12).jpg",
    name: "Bike Lights",
    type: "Safety Gear",
    price: 25.0,
    description:
      "Front and rear lights for visibility during low-light conditions.",
  },
  {
    accessoriesImg: "./imgs/accesories/accessory (8).png",
    accessoriesImg2: "./imgs/accesories/accessory (9).png",
    accessoriesImg3: "./imgs/accesories/accessory (10).png",
    accessoriesImg4: "./imgs/accesories/accessory (11).jpg",
    name: "Bike pomp",
    type: "Maintenance",
    price: 12.75,
    description: "Essential tools for repairing punctures quickly on the go.",
  },
  {
    accessoriesImg: "./imgs/accesories/accessory (7).png",
    accessoriesImg2: "./imgs/accesories/accessory (8).png",
    accessoriesImg3: "./imgs/accesories/accessory (9).png",
    accessoriesImg4: "./imgs/accesories/accessory (10).png",
    name: "Bike Lock",
    type: "Security",
    price: 40.25,
    description: "Durable lock to secure your bike when not in use.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (1).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "GripMaster",
    type: "Apparel",
    price: 20.99,
    description: "These gloves feature advanced grip technology and breathable materials, providing superior control and comfort for all cycling conditions.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (2).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "TrailTough",
    type: "Apparel",
    price: 20.99,
    description: "Designed for rugged off-road adventures, TrailTough gloves offer reinforced protection and extra padding to withstand the toughest trails.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (3).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "UrbanFlex",
    type: "Apparel",
    price: 26.99,
    description: " Perfect for city cyclists, UrbanFlex gloves combine sleek design with flexible, lightweight materials for enhanced maneuverability and style.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (4).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "SpeedGrip",
    type: "Apparel",
    price: 20.99,
    description: "Engineered for speed and performance, SpeedGrip gloves deliver a snug fit with aerodynamic features to reduce drag and enhance control during fast rides.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (6).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "EnduroGuard",
    type: "Apparel",
    price: 28.99,
    description: "Built for endurance and long-distance rides, EnduroGuard gloves provide optimal cushioning and support to keep your hands comfortable on extended journeys.",
  },
  {
    accessoriesImg: "./imgs/gloves/gloves (5).png",
    accessoriesImg2: "./imgs/gloves/gloves (2).png",
    accessoriesImg3: "./imgs/gloves/gloves (3).png",
    accessoriesImg4: "./imgs/gloves/gloves (4).png",
    name: "AeroShield",
    type: "Apparel",
    price: 20.99,
    description: "Featuring wind-resistant and breathable fabrics, AeroShield gloves are ideal for high-speed road cycling, ensuring maximum comfort and protection against the elements.",
  },
  {
    accessoriesImg: "./imgs/accesories/accessory (5).png",
    accessoriesImg2: "./imgs/accesories/accessory (6).jpg",
    accessoriesImg3: "./imgs/accesories/accessory (7).jpg",
    accessoriesImg4: "./imgs/accesories/accessory (8).jpg",
    name: "Bike Rack",
    type: "Transportation",
    price: 65.0,
    description:
      "Rack for attaching your bike to your vehicle for transportation.",
  },


  {
    accessoriesImg: "./imgs/accesories/accessory (2).png",
    accessoriesImg2: "./imgs/accesories/accessory (3).jpg",
    accessoriesImg3: "./imgs/accesories/accessory (4).jpg",
    accessoriesImg4: "./imgs/accesories/accessory (5).png",
    name: "Bike Saddle",
    type: "Storage",
    price: 18.99,
    description:
    "Small bike saddle for attachement",
  },
  {
    accessoriesImg: "./imgs/accesories/saddle (1).png",
    accessoriesImg2:  "./imgs/accesories/saddle (2).png",
    accessoriesImg3:  "./imgs/accesories/saddle (3).png",
    accessoriesImg4:  "./imgs/accesories/saddle (4).png",
    name: "Bike Saddle",
    type: "Storage",
    price: 18.99,
    description:
      "Small bike saddle for attachement",
  },
  {
    accessoriesImg: "./imgs/accesories/saddle (4).png",
    accessoriesImg2:  "./imgs/accesories/saddle (2).png",
    accessoriesImg3:  "./imgs/accesories/saddle (3).png",
    accessoriesImg4:  "./imgs/accesories/saddle (4).png",
    name: "Bike Saddle",
    type: "Storage",
    price: 18.99,
    description:
      "Small bike saddle for attachement",
  },
  {
    accessoriesImg: "./imgs/accesories/saddle (2).png",
    accessoriesImg2:  "./imgs/accesories/saddle (2).png",
    accessoriesImg3:  "./imgs/accesories/saddle (3).png",
    accessoriesImg4:  "./imgs/accesories/saddle (4).png",
    name: "Bike Saddle",
    type: "Storage",
    price: 18.99,
    description:
      "Small bike saddle for attachement",
  },
  {
    accessoriesImg: "./imgs/accesories/saddle (3).png",
    accessoriesImg2:  "./imgs/accesories/saddle (2).png",
    accessoriesImg3:  "./imgs/accesories/saddle (3).png",
    accessoriesImg4:  "./imgs/accesories/saddle (4).png",
    name: "Bike Saddle",
    type: "Storage",
    price: 18.99,
    description:
      "Small bike saddle for attachement",
  },
 
];

const BikesFat = [
  {
    id: 1,
    img: "./imgs/bikes-transparent/bike-top (1).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Model A",
    location: "edinburgh",
    price: 30.99,
    description:
      "Your perfect companion for exploring Edinburgh's scenic routes with ease.",
    type: "electric",
    speed: 64,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
  {
    id: 2,
    img: "./imgs/bikes-transparent/bike-top (2).png",
    img2: "./imgs/bikes-transparent/bike-top (1).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Trailblazer X",
    location: "Edinburgh",
    price: 35.5,
    description:
      "Unmatched speed and rugged durability for conquering Edinburgh's trails like a pro.",
    type: "electric",
    speed: 70,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
  {
    id: 3,
    img: "./imgs/bikes-transparent/bike-top (3).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Explorer Pro",
    location: "Edinburgh",
    price: 28.99,
    description:
      "Explorer Pro: Discover Edinburgh's landscapes with reliability and versatility.",
    type: "electric",
    speed: 60,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
  {
    id: 4,
    img: "./imgs/bikes-transparent/bike-top (4).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Thunderbolt XT",
    location: "Edinburgh",
    price: 32.75,
    description:
      "Experience the thrill of speed through Edinburgh's diverse terrain.",
    type: "electric",
    speed: 68,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
  {
    id: 5,
    img: "./imgs/bikes-transparent/bike-top (5).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Adventure Seeker",
    location: "Edinburgh",
    price: 31.99,
    description:
      "Adventure Seeker: Unleash your adventurous spirit on Edinburgh's urban streets and off-road trails.",
    type: "electric",
    speed: 65,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
];
const BikesHybrid = [
  {
    id: 1,
    img: "./imgs/bikes-transparent/bike-top (14).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Urban Commuter",
    location: "Glasgow",
    price: 39.99,
    description:
      "Urban Commuter: Navigate Glasgow's streets with ease and comfort on this versatile hybrid bike.",
    type: "hybrid",
    suspension: "none",
    speed: 62,
    frame: "Carbon Fiber",
    grupset: "SRAM",
    brakingSystem: "Rim brakes",
    wheel: "27.5-inch",
    velg: "Carbon Fiber",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "Look",
  },
  {
    id: 2,
    img: "./imgs/bikes-transparent/bike-top (15).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "City Explorer",
    location: "Edinburgh",
    price: 42.5,
    description:
      "City Explorer: Discover Edinburgh's hidden gems and scenic routes on this reliable hybrid bike.",
    type: "hybrid",
    suspension: "front",
    speed: 61,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
  {
    id: 3,
    img: "./imgs/bikes-transparent/bike-top (16).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Crossroad Cruiser",
    location: "Aberdeen",
    price: 45.99,
    description:
      "Crossroad Cruiser: Cruise through Aberdeen's urban and rural landscapes in style and comfort.",
    type: "hybrid",
    suspension: "none",
    speed: 69,
    frame: "Carbon Fiber",
    grupset: "Shimano",
    brakingSystem: "Rim brakes",
    wheel: "29-inch",
    velg: "Carbon Fiber",
    stang: "Alloy",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "SPD",
  },
  {
    id: 4,
    img: "./imgs/bikes-transparent/bike-top (17).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Adventure Hybrid",
    location: "Dundee",
    price: 48.75,
    description:
      "Adventure Hybrid: Embark on thrilling journeys through Dundee's diverse terrain on this versatile hybrid bike.",
    type: "hybrid",
    suspension: "front",
    speed: 64,
    frame: "Steel",
    grupset: "SRAM",
    brakingSystem: "Disc brakes",
    wheel: "27.5-inch",
    velg: "Alloy",
    stang: "Steel",
    pedal: "Flat",
    transmission: "1x",
    cleat: "Look",
  },
  {
    id: 5,
    img: "./imgs/bikes-transparent/bike-top (1).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Metro Trekker",
    location: "Inverness",
    price: 52.99,
    description:
      "Metro Trekker: Explore Inverness's city streets and outskirts with confidence and agility on this premium hybrid bike.",
    type: "hybrid",
    suspension: "front",
    speed: 59,
    frame: "Aluminum",
    grupset: "Campagnolo",
    brakingSystem: "Rim brakes",
    wheel: "26-inch",
    velg: "Steel",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "3x",
    cleat: "Time",
  },
];
const BikesMountain = [
  {
    id: 1,
    img: "./imgs/bikes-transparent/bike-top (6).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Trailblazer 5000",
    location: "Edinburgh",
    price: 45.99,
    description:
      "Trailblazer 5000: Dominate the trails of Edinburgh with precision and power.",
    type: "mountain",
    suspension: "full",
    gears: 21,
    frame: "Steel",
    grupset: "Campagnolo",
    brakingSystem: "Disc brakes",
    wheel: "29-inch",
    velg: "Steel",
    stang: "Steel",
    pedal: "Flat",
    transmission: "3x",
    cleat: "Time",
  },
  {
    id: 2,
    img: "./imgs/bikes-transparent/bike-top (7).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Summit Slayer",
    location: "Edinburgh",
    price: 52.5,
    description:
      "Summit Slayer: Conquer Edinburgh's toughest peaks with unmatched agility and control.",
    type: "mountain",
    suspension: "front",
    speed: 55,
    frame: "Carbon Fiber",
    grupset: "Shimano",
    brakingSystem: "Rim brakes",
    wheel: "29-inch",
    velg: "Carbon Fiber",
    stang: "Alloy",
    pedal: "Clipless",
    transmission: "2x",
    cleat: "SPD",
  },
  {
    id: 3,
    img: "./imgs/bikes-transparent/bike-top (8).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Ridge Rider Pro",
    location: "Edinburgh",
    price: 49.99,
    description:
      "Ridge Rider Pro: Explore Edinburgh's rugged terrain with confidence and style.",
    type: "mountain",
    suspension: "full",
    speed: 55,
    frame: "Steel",
    grupset: "SRAM",
    brakingSystem: "Disc brakes",
    wheel: "27.5-inch",
    velg: "Alloy",
    stang: "Steel",
    pedal: "Flat",
    transmission: "1x",
    cleat: "Look",
  },
  {
    id: 4,
    img: "./imgs/bikes-transparent/bike-top (12).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Alpine Assault",
    location: "Edinburgh",
    price: 48.75,
    description:
      "Alpine Assault: Tackle Edinburgh's mountainous trails with ease and speed.",
    type: "mountain",
    suspension: "front",
    speed: 68,
    frame: "Aluminum",
    grupset: "Campagnolo",
    brakingSystem: "Rim brakes",
    wheel: "26-inch",
    velg: "Steel",
    stang: "Carbon Fiber",
    pedal: "Clipless",
    transmission: "3x",
    cleat: "Time",
  },
  {
    id: 5,
    img: "./imgs/bikes-transparent/bike-top (13).png",
    img2: "./imgs/bikes-transparent/bike-top (2).png",
    img3: "./imgs/bikes-transparent/bike-top (3).png",
    name: "Peak Performance",
    location: "Edinburgh",
    price: 55.99,
    description:
      "Peak Performance: Reach new heights of performance on Edinburgh's challenging terrain.",
    type: "mountain",
    suspension: "full",
    speed: 75,
    frame: "Aluminum",
    grupset: "Shimano",
    brakingSystem: "Disc brakes",
    wheel: "26-inch",
    velg: "Alloy",
    stang: "Alloy",
    pedal: "Flat",
    transmission: "1x",
    cleat: "SPD",
  },
];
